import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import type { Field, Introspection, TypeRef } from './types.js';

export interface EmitOptions {
  /** Parsed introspection. */
  schema: Introspection;
  /** Absolute path to write generated files into. */
  outDir: string;
  /** Override built-in scalar mapping. Merged onto defaults. */
  scalars?: Record<string, string>;
  /**
   * Field paths whose TS type should be `JsonObject` regardless of schema kind.
   * Wildcards: `"*.props"` matches any parent. Default: `["*.props", "*.metadata"]`.
   */
  freeSchemaFields?: string[];
  /** Name of the npm package that exposes the runtime (`createUseGql`). Defaults to "gqlx". */
  runtimePackage?: string;
}

const DEFAULT_SCALARS: Record<string, string> = {
  String: 'string',
  Int: 'number',
  Float: 'number',
  Boolean: 'boolean',
  ID: 'string',
  Date: 'string',
  DateTime: 'string',
  JSON: 'JsonObject',
  JSONObject: 'JsonObject',
};

const DEFAULT_FREE_SCHEMA_FIELDS = ['*.props', '*.metadata'];

function isInternal(name: string | null | undefined) {
  return !!name && name.startsWith('__');
}

function unwrap(t: TypeRef): { named: TypeRef; nullable: boolean; list: boolean; listNullable: boolean } {
  let nullable = true;
  let list = false;
  let listNullable = true;
  let cur: TypeRef = t;
  if (cur.kind === 'NON_NULL') {
    nullable = false;
    cur = cur.ofType!;
  }
  if (cur.kind === 'LIST') {
    list = true;
    cur = cur.ofType!;
    if (cur.kind === 'NON_NULL') {
      listNullable = false;
      cur = cur.ofType!;
    }
  }
  return { named: cur, nullable, list, listNullable };
}

function gqlTypeString(t: TypeRef): string {
  if (t.kind === 'NON_NULL') return `${gqlTypeString(t.ofType!)}!`;
  if (t.kind === 'LIST') return `[${gqlTypeString(t.ofType!)}]`;
  return t.name!;
}

function banner(name: string) {
  return `/* eslint-disable */\n// AUTO-GENERATED by gqlx — do not edit by hand.\n// File: ${name}\n\n`;
}

export function emit(options: EmitOptions): { fileCount: number; outDir: string } {
  const { schema, outDir, runtimePackage = 'gqlx' } = options;
  const SCALAR_MAP = { ...DEFAULT_SCALARS, ...(options.scalars ?? {}) };
  const FREE_SCHEMA_FIELDS = new Set(options.freeSchemaFields ?? DEFAULT_FREE_SCHEMA_FIELDS);

  function tsTypeOf(t: TypeRef): string {
    const { named, nullable, list, listNullable } = unwrap(t);
    let inner: string;
    switch (named.kind) {
      case 'SCALAR':
        inner = SCALAR_MAP[named.name!] ?? 'unknown';
        break;
      case 'ENUM':
      case 'INPUT_OBJECT':
      case 'OBJECT':
      case 'INTERFACE':
      case 'UNION':
        inner = named.name!;
        break;
      default:
        inner = 'unknown';
    }
    if (list) {
      const item = listNullable ? `${inner} | null` : inner;
      const arr = `Array<${item}>`;
      return nullable ? `${arr} | null` : arr;
    }
    return nullable ? `${inner} | null` : inner;
  }

  function matchesFreeSchema(parent: string, field: string): boolean {
    return FREE_SCHEMA_FIELDS.has(`${parent}.${field}`) || FREE_SCHEMA_FIELDS.has(`*.${field}`);
  }

  const sch = schema.__schema;
  const types = sch.types.filter((t) => !isInternal(t.name));
  const objects = types.filter((t) => t.kind === 'OBJECT');
  const interfaces = types.filter((t) => t.kind === 'INTERFACE');
  const unions = types.filter((t) => t.kind === 'UNION');
  const inputs = types.filter((t) => t.kind === 'INPUT_OBJECT');
  const enums = types.filter((t) => t.kind === 'ENUM');

  mkdirSync(outDir, { recursive: true });
  let fileCount = 0;
  const write = (name: string, body: string) => {
    writeFileSync(resolve(outDir, name), body);
    fileCount++;
  };

  // ---------- scalars.ts ----------
  write(
    'scalars.ts',
    banner('scalars.ts') +
      `export type JsonValue = string | number | boolean | null | JsonValue[] | { [k: string]: JsonValue };\n` +
      `export type JsonObject = { [k: string]: JsonValue };\n`,
  );

  // ---------- enums.ts ----------
  const enumBody = enums.length
    ? enums
        .map((e) => `export type ${e.name} = ${(e.enumValues ?? []).map((v) => JSON.stringify(v.name)).join(' | ') || 'never'};`)
        .join('\n')
    : 'export {};';
  write('enums.ts', banner('enums.ts') + enumBody + '\n');

  // ---------- inputs.ts ----------
  const inputBody = inputs.length
    ? inputs
        .map((it) => {
          const fields = (it.inputFields ?? [])
            .map((f) => {
              const { nullable } = unwrap(f.type);
              const optional = nullable ? '?' : '';
              return `  ${f.name}${optional}: ${tsTypeOf(f.type)};`;
            })
            .join('\n');
          return `export interface ${it.name} {\n${fields}\n}`;
        })
        .join('\n\n')
    : 'export {};';
  write(
    'inputs.ts',
    banner('inputs.ts') +
      `import type { JsonObject } from './scalars';\n` +
      enums.map((e) => `import type { ${e.name} } from './enums';`).join('\n') +
      `\n\n${inputBody}\n`,
  );

  // ---------- schema.ts ----------
  const schemaParts: string[] = [];
  for (const obj of [...objects, ...interfaces]) {
    if (!obj.fields) continue;
    const lines = obj.fields.map((f) => {
      const tsType = matchesFreeSchema(obj.name, f.name) ? 'JsonObject | null' : tsTypeOf(f.type);
      return `  ${f.name}: ${tsType};`;
    });
    schemaParts.push(`export interface ${obj.name} {\n${lines.join('\n')}\n}`);
  }
  for (const u of unions) {
    const members = (u.possibleTypes ?? []).map((p) => p.name).join(' | ') || 'never';
    schemaParts.push(`export type ${u.name} = ${members};`);
  }
  write(
    'schema.ts',
    banner('schema.ts') +
      `import type { JsonObject } from './scalars';\n` +
      enums.map((e) => `import type { ${e.name} } from './enums';`).join('\n') +
      `\n\n${schemaParts.join('\n\n')}\n`,
  );

  // ---------- wrappers detection ----------
  const wrappers: Record<string, { field: 'items' | 'data'; inner: string }> = {};
  for (const obj of objects) {
    if (!obj.fields || obj.fields.length !== 1) continue;
    const f = obj.fields[0]!;
    if (f.name !== 'items' && f.name !== 'data') continue;
    const { named } = unwrap(f.type);
    if (named.kind !== 'OBJECT' && named.kind !== 'INTERFACE') continue;
    wrappers[obj.name] = { field: f.name as 'items' | 'data', inner: named.name! };
  }

  // ---------- select.ts ----------
  function selectableChild(t: TypeRef, parent: string, field: string): string | null {
    if (matchesFreeSchema(parent, field)) return null;
    const { named } = unwrap(t);
    if (named.kind === 'OBJECT' || named.kind === 'INTERFACE' || named.kind === 'UNION') return named.name!;
    return null;
  }
  const argsTypeName = (parent: string, field: string) => `${parent}_${field}_Args`;
  const rootTypeNames = new Set<string>();
  if (sch.queryType?.name) rootTypeNames.add(sch.queryType.name);
  if (sch.mutationType?.name) rootTypeNames.add(sch.mutationType.name);

  const selectParts: string[] = [];
  for (const obj of [...objects, ...interfaces]) {
    if (!obj.fields) continue;
    const isRoot = rootTypeNames.has(obj.name);
    const lines = obj.fields.map((f) => {
      const child = selectableChild(f.type, obj.name, f.name);
      const hasArgs = (f.args ?? []).length > 0;
      const configExtra = isRoot ? '; config?: AxiosRequestConfig' : '';
      if (!child && !hasArgs) return `  ${f.name}?: true;`;
      if (!child && hasArgs) {
        const argsRef = argsTypeName(obj.name, f.name);
        return isRoot
          ? `  ${f.name}?: true | (${argsRef} & { config?: AxiosRequestConfig });`
          : `  ${f.name}?: true | (${argsRef});`;
      }
      const childSelect = isRoot && wrappers[child!] ? `${wrappers[child!].inner}Select` : `${child}Select`;
      const node = hasArgs
        ? `({ include: ${childSelect}${configExtra} } & ${argsTypeName(obj.name, f.name)})`
        : `{ include: ${childSelect}${configExtra} }`;
      return `  ${f.name}?: true | ${node};`;
    });
    selectParts.push(`export type ${obj.name}Select = {\n${lines.join('\n')}\n};`);
  }
  for (const u of unions) {
    const members = u.possibleTypes ?? [];
    const onLines = members.map((m) => `    ${m.name}?: ${m.name}Select;`);
    selectParts.push(`export type ${u.name}Select = {\n  __typename?: true;\n  __on?: {\n${onLines.join('\n')}\n  };\n};`);
  }

  // ---------- args.ts ----------
  const argsParts: string[] = [];
  const emitArgs = (parent: string, fields: Field[]) => {
    for (const f of fields) {
      if (!(f.args && f.args.length)) continue;
      const lines = f.args.map((a) => {
        const { nullable } = unwrap(a.type);
        const optional = nullable || a.defaultValue !== null ? '?' : '';
        return `  ${a.name}${optional}: ${tsTypeOf(a.type)};`;
      });
      argsParts.push(`export interface ${argsTypeName(parent, f.name)} {\n${lines.join('\n')}\n}`);
    }
  };
  for (const obj of [...objects, ...interfaces]) if (obj.fields) emitArgs(obj.name, obj.fields);
  write(
    'args.ts',
    banner('args.ts') +
      `import type { JsonObject } from './scalars';\n` +
      enums.map((e) => `import type { ${e.name} } from './enums';`).join('\n') +
      '\n' +
      inputs.map((i) => `import type { ${i.name} } from './inputs';`).join('\n') +
      `\n\n${argsParts.length ? argsParts.join('\n\n') : 'export {};'}\n`,
  );

  const argTypeImports = [...objects, ...interfaces]
    .flatMap((o) => (o.fields ?? []).filter((f) => f.args?.length).map((f) => argsTypeName(o.name, f.name)))
    .map((n) => `import type { ${n} } from './args';`)
    .join('\n');
  write(
    'select.ts',
    banner('select.ts') + `import type { AxiosRequestConfig } from 'axios';\n${argTypeImports}\n\n${selectParts.join('\n\n')}\n`,
  );

  // ---------- runtime descriptors ----------
  const fieldArgs: Record<string, Record<string, Record<string, string>>> = {};
  for (const obj of [...objects, ...interfaces]) {
    if (!obj.fields) continue;
    for (const f of obj.fields) {
      if (!f.args?.length) continue;
      const bucket = (fieldArgs[obj.name] ??= {});
      bucket[f.name] = Object.fromEntries(f.args.map((a) => [a.name, gqlTypeString(a.type)]));
    }
  }
  write(
    'field-args.ts',
    banner('field-args.ts') + `export const FIELD_ARGS = ${JSON.stringify(fieldArgs, null, 2)} as const;\n`,
  );

  const fieldTypes: Record<string, Record<string, string>> = {};
  for (const obj of [...objects, ...interfaces]) {
    if (!obj.fields) continue;
    for (const f of obj.fields) {
      const { named } = unwrap(f.type);
      if (named.kind === 'OBJECT' || named.kind === 'INTERFACE' || named.kind === 'UNION') {
        const bucket = (fieldTypes[obj.name] ??= {});
        bucket[f.name] = named.name!;
      }
    }
  }
  write(
    'field-types.ts',
    banner('field-types.ts') + `export const FIELD_TYPES = ${JSON.stringify(fieldTypes, null, 2)} as const;\n`,
  );

  write(
    'wrappers.ts',
    banner('wrappers.ts') + `export const WRAPPERS = ${JSON.stringify(wrappers, null, 2)} as const;\n`,
  );

  // ---------- root.ts ----------
  const queryName = sch.queryType?.name ?? 'Query';
  const mutationName = sch.mutationType?.name ?? null;
  const querySelectName = `${queryName}Select`;
  const mutationSelectName = mutationName ? `${mutationName}Select` : null;
  const aliasIfNeeded = (orig: string, target: string) => (orig === target ? orig : `${orig} as ${target}`);
  const reExports = [aliasIfNeeded(querySelectName, 'QuerySelect')];
  if (mutationSelectName) reExports.push(aliasIfNeeded(mutationSelectName, 'MutationSelect'));
  write(
    'root.ts',
    banner('root.ts') +
      `export type { ${reExports.join(', ')} } from './select';\n` +
      (mutationSelectName ? '' : `export type MutationSelect = never;\n`) +
      `export const ROOT_QUERY_TYPE = ${JSON.stringify(queryName)} as const;\n` +
      `export const ROOT_MUTATION_TYPE = ${JSON.stringify(mutationName)} as const;\n`,
  );

  // ---------- client.ts (the user-facing entry) ----------
  write(
    'client.ts',
    banner('client.ts') +
      `import { createClient, type ClientOptions } from ${JSON.stringify(runtimePackage)};\n\n` +
      `import { FIELD_ARGS } from './field-args';\n` +
      `import { FIELD_TYPES } from './field-types';\n` +
      `import { WRAPPERS } from './wrappers';\n` +
      `import { ROOT_QUERY_TYPE, ROOT_MUTATION_TYPE } from './root';\n` +
      `import type { ${queryName}${mutationName ? `, ${mutationName}` : ''} } from './schema';\n` +
      `import type { QuerySelect, MutationSelect } from './root';\n\n` +
      `export function createUseGql(options: ClientOptions) {\n` +
      `  return createClient<${queryName}, ${mutationName ?? 'never'}, QuerySelect, MutationSelect>(\n` +
      `    {\n` +
      `      FIELD_ARGS: FIELD_ARGS as any,\n` +
      `      FIELD_TYPES: FIELD_TYPES as any,\n` +
      `      WRAPPERS: WRAPPERS as any,\n` +
      `      ROOT_QUERY_TYPE,\n` +
      `      ROOT_MUTATION_TYPE,\n` +
      `    },\n` +
      `    options,\n` +
      `  );\n` +
      `}\n`,
  );

  // ---------- index.ts ----------
  write(
    'index.ts',
    banner('index.ts') +
      `export * from './scalars';\n` +
      `export * from './enums';\n` +
      `export * from './inputs';\n` +
      `export * from './schema';\n` +
      `export * from './select';\n` +
      `export * from './args';\n` +
      `export * from './root';\n` +
      `export { FIELD_ARGS } from './field-args';\n` +
      `export { FIELD_TYPES } from './field-types';\n` +
      `export { WRAPPERS } from './wrappers';\n` +
      `export { createUseGql } from './client';\n`,
  );

  // ---------- package.json (lets bare-name resolution work for the default `.gqlx` location) ----------
  write(
    'package.json',
    JSON.stringify(
      {
        name: '.gqlx',
        type: 'module',
        main: './index.js',
        types: './index.ts',
      },
      null,
      2,
    ) + '\n',
  );

  return { fileCount, outDir };
}
