#!/usr/bin/env tsx
/**
 * Prisma-style GraphQL client codegen.
 *
 * Reads graphql.schema.json (introspection) and emits:
 *   app/gql-client/generated/
 *     ├── scalars.ts       — JsonObject + scalar mapping
 *     ├── enums.ts         — TS string-literal unions for GraphQL enums
 *     ├── inputs.ts        — INPUT_OBJECT types (for `where`, `data`, `input`, …)
 *     ├── schema.ts        — OBJECT / INTERFACE / UNION model types
 *     ├── select.ts        — Prisma-style Select<T> types
 *     ├── args.ts          — Per-field argument types
 *     ├── field-args.ts    — Runtime descriptor used by the builder
 *     ├── field-types.ts   — Runtime parent→field→childType map
 *     └── root.ts          — QuerySelect / MutationSelect / Infer helpers
 *
 * Run with: tsx scripts/gen-gql.ts
 */

import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

type Kind = 'SCALAR' | 'OBJECT' | 'INTERFACE' | 'UNION' | 'ENUM' | 'INPUT_OBJECT' | 'LIST' | 'NON_NULL';
type TypeRef = { kind: Kind; name: string | null; ofType: TypeRef | null };
type InputValue = { name: string; type: TypeRef; defaultValue: string | null };
type Field = { name: string; args: InputValue[]; type: TypeRef };
type GqlType = {
  kind: Kind;
  name: string;
  fields: Field[] | null;
  inputFields: InputValue[] | null;
  interfaces: { name: string }[] | null;
  enumValues: { name: string }[] | null;
  possibleTypes: { name: string }[] | null;
};
type Introspection = {
  __schema: {
    queryType: { name: string } | null;
    mutationType: { name: string } | null;
    subscriptionType: { name: string } | null;
    types: GqlType[];
  };
};

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const SCHEMA_PATH = resolve(ROOT, 'graphql.schema.json');
const OUT_DIR = resolve(ROOT, 'app/gql-client/generated');

const SCALAR_MAP: Record<string, string> = {
  String: 'string',
  Int: 'number',
  Float: 'number',
  Boolean: 'boolean',
  ID: 'string',
  Date: 'string',
  DateTime: 'string',
  JSON: 'JsonObject',
  JSONObject: 'JsonObject',
};

// Field paths that should be typed as JsonObject regardless of their GraphQL type.
// Adjust as you discover more dynamic-shape leaves on the server.
const FREE_SCHEMA_FIELDS = new Set<string>(['*.props', '*.metadata']);

function isInternal(name: string | null | undefined) {
  return !!name && name.startsWith('__');
}

function unwrap(t: TypeRef): { named: TypeRef; nullable: boolean; list: boolean; listNullable: boolean } {
  let nullable = true;
  let list = false;
  let listNullable = true;
  let cur: TypeRef = t;
  if (cur.kind === 'NON_NULL') {
    nullable = false;
    cur = cur.ofType!;
  }
  if (cur.kind === 'LIST') {
    list = true;
    cur = cur.ofType!;
    if (cur.kind === 'NON_NULL') {
      listNullable = false;
      cur = cur.ofType!;
    }
  }
  return { named: cur, nullable, list, listNullable };
}

function tsTypeOf(t: TypeRef): string {
  const { named, nullable, list, listNullable } = unwrap(t);
  let inner: string;
  switch (named.kind) {
    case 'SCALAR':
      inner = SCALAR_MAP[named.name!] ?? 'unknown';
      break;
    case 'ENUM':
      inner = named.name!;
      break;
    case 'INPUT_OBJECT':
      inner = named.name!;
      break;
    case 'OBJECT':
    case 'INTERFACE':
    case 'UNION':
      inner = named.name!;
      break;
    default:
      inner = 'unknown';
  }
  if (list) {
    const item = listNullable ? `${inner} | null` : inner;
    const arr = `Array<${item}>`;
    return nullable ? `${arr} | null` : arr;
  }
  return nullable ? `${inner} | null` : inner;
}

function gqlTypeString(t: TypeRef): string {
  if (t.kind === 'NON_NULL') return `${gqlTypeString(t.ofType!)}!`;
  if (t.kind === 'LIST') return `[${gqlTypeString(t.ofType!)}]`;
  return t.name!;
}

function matchesFreeSchema(parent: string, field: string): boolean {
  return FREE_SCHEMA_FIELDS.has(`${parent}.${field}`) || FREE_SCHEMA_FIELDS.has(`*.${field}`);
}

function banner(name: string) {
  return `/* eslint-disable */\n// AUTO-GENERATED by scripts/gen-gql.ts — do not edit by hand.\n// Source: graphql.schema.json\n// File: ${name}\n\n`;
}

function main() {
  const raw = JSON.parse(readFileSync(SCHEMA_PATH, 'utf8')) as Introspection | { data: Introspection };
  const intro: Introspection = (raw as any).__schema ? (raw as Introspection) : (raw as { data: Introspection }).data;
  const schema = intro.__schema;

  const types = schema.types.filter((t) => !isInternal(t.name));

  const objects = types.filter((t) => t.kind === 'OBJECT');
  const interfaces = types.filter((t) => t.kind === 'INTERFACE');
  const unions = types.filter((t) => t.kind === 'UNION');
  const inputs = types.filter((t) => t.kind === 'INPUT_OBJECT');
  const enums = types.filter((t) => t.kind === 'ENUM');

  mkdirSync(OUT_DIR, { recursive: true });

  // -------- scalars.ts --------
  writeFileSync(
    resolve(OUT_DIR, 'scalars.ts'),
    banner('scalars.ts') +
      `export type JsonValue = string | number | boolean | null | JsonValue[] | { [k: string]: JsonValue };\n` +
      `export type JsonObject = { [k: string]: JsonValue };\n`,
  );

  // -------- enums.ts --------
  const enumBody = enums.length
    ? enums
        .map((e) => `export type ${e.name} = ${(e.enumValues ?? []).map((v) => JSON.stringify(v.name)).join(' | ') || 'never'};`)
        .join('\n')
    : 'export {};';
  writeFileSync(resolve(OUT_DIR, 'enums.ts'), banner('enums.ts') + enumBody + '\n');

  // -------- inputs.ts --------
  const inputBody = inputs.length
    ? inputs
        .map((it) => {
          const fields = (it.inputFields ?? [])
            .map((f) => {
              const { nullable } = unwrap(f.type);
              const optional = nullable ? '?' : '';
              return `  ${f.name}${optional}: ${tsTypeOf(f.type)};`;
            })
            .join('\n');
          return `export interface ${it.name} {\n${fields}\n}`;
        })
        .join('\n\n')
    : 'export {};';
  writeFileSync(
    resolve(OUT_DIR, 'inputs.ts'),
    banner('inputs.ts') +
      `import type { JsonObject } from './scalars';\n` +
      enums.map((e) => `import type { ${e.name} } from './enums';`).join('\n') +
      `\n\n${inputBody}\n`,
  );

  // -------- schema.ts (OBJECT / INTERFACE / UNION) --------
  const schemaParts: string[] = [];

  for (const obj of [...objects, ...interfaces]) {
    if (!obj.fields) continue;
    const lines = obj.fields.map((f) => {
      let tsType: string;
      if (matchesFreeSchema(obj.name, f.name)) tsType = 'JsonObject | null';
      else tsType = tsTypeOf(f.type);
      return `  ${f.name}: ${tsType};`;
    });
    schemaParts.push(`export interface ${obj.name} {\n${lines.join('\n')}\n}`);
  }

  for (const u of unions) {
    const members = (u.possibleTypes ?? []).map((p) => p.name).join(' | ') || 'never';
    schemaParts.push(`export type ${u.name} = ${members};`);
  }

  writeFileSync(
    resolve(OUT_DIR, 'schema.ts'),
    banner('schema.ts') +
      `import type { JsonObject } from './scalars';\n` +
      enums.map((e) => `import type { ${e.name} } from './enums';`).join('\n') +
      `\n\n${schemaParts.join('\n\n')}\n`,
  );

  // -------- wrappers (Items/Data serializer detection) --------
  // A wrapper is an OBJECT with exactly one field named `items` or `data` whose
  // value is an OBJECT/INTERFACE. The user-facing select for a field that returns
  // a wrapper bypasses the wrapper layer: callers write `include: { …innerFields }`
  // and the builder re-inserts `items { … }` / `data { … }` at runtime.
  const wrappers: Record<string, { field: 'items' | 'data'; inner: string }> = {};
  for (const obj of objects) {
    if (!obj.fields || obj.fields.length !== 1) continue;
    const f = obj.fields[0]!;
    if (f.name !== 'items' && f.name !== 'data') continue;
    const { named } = unwrap(f.type);
    if (named.kind !== 'OBJECT' && named.kind !== 'INTERFACE') continue;
    wrappers[obj.name] = { field: f.name, inner: named.name! };
  }

  // -------- select.ts --------
  // For each OBJECT (and INTERFACE / UNION), produce a Select shape.
  // - Scalar / enum / JSON leaves: `field?: true`
  // - Object / interface / union: `field?: true | { include: ChildSelect; ...args }`
  const selectParts: string[] = [];

  function selectableChild(t: TypeRef, parent: string, field: string): string | null {
    if (matchesFreeSchema(parent, field)) return null;
    const { named } = unwrap(t);
    if (named.kind === 'OBJECT' || named.kind === 'INTERFACE' || named.kind === 'UNION') return named.name!;
    return null;
  }

  function argsTypeName(parent: string, field: string) {
    return `${parent}_${field}_Args`;
  }

  const rootTypeNames = new Set<string>();
  if (schema.queryType?.name) rootTypeNames.add(schema.queryType.name);
  if (schema.mutationType?.name) rootTypeNames.add(schema.mutationType.name);

  for (const obj of [...objects, ...interfaces]) {
    if (!obj.fields) continue;
    const isRoot = rootTypeNames.has(obj.name);
    const lines = obj.fields.map((f) => {
      const child = selectableChild(f.type, obj.name, f.name);
      const hasArgs = (f.args ?? []).length > 0;
      const configExtra = isRoot ? '; config?: AxiosRequestConfig' : '';
      if (!child && !hasArgs) return `  ${f.name}?: true;`;
      if (!child && hasArgs) {
        const argsRef = argsTypeName(obj.name, f.name);
        return isRoot
          ? `  ${f.name}?: true | (${argsRef} & { config?: AxiosRequestConfig });`
          : `  ${f.name}?: true | (${argsRef});`;
      }
      // For wrapper-returning fields (only meaningful at root level), drop the
      // wrapper layer in the select — callers write the inner serializer's fields
      // directly under `include`.
      const childSelect = isRoot && wrappers[child!] ? `${wrappers[child!].inner}Select` : `${child}Select`;
      const node = hasArgs
        ? `({ include: ${childSelect}${configExtra} } & ${argsTypeName(obj.name, f.name)})`
        : `{ include: ${childSelect}${configExtra} }`;
      return `  ${f.name}?: true | ${node};`;
    });
    selectParts.push(`export type ${obj.name}Select = {\n${lines.join('\n')}\n};`);
  }

  for (const u of unions) {
    const members = u.possibleTypes ?? [];
    // For unions we expose an `__on` fragment selection.
    const onLines = members.map((m) => `    ${m.name}?: ${m.name}Select;`);
    selectParts.push(`export type ${u.name}Select = {\n  __typename?: true;\n  __on?: {\n${onLines.join('\n')}\n  };\n};`);
  }

  // -------- args.ts --------
  const argsParts: string[] = [];
  function emitArgs(parent: string, fields: Field[]) {
    for (const f of fields) {
      if (!(f.args && f.args.length)) continue;
      const lines = f.args.map((a) => {
        const { nullable } = unwrap(a.type);
        const optional = nullable || a.defaultValue !== null ? '?' : '';
        return `  ${a.name}${optional}: ${tsTypeOf(a.type)};`;
      });
      argsParts.push(`export interface ${argsTypeName(parent, f.name)} {\n${lines.join('\n')}\n}`);
    }
  }
  for (const obj of [...objects, ...interfaces]) if (obj.fields) emitArgs(obj.name, obj.fields);

  writeFileSync(
    resolve(OUT_DIR, 'args.ts'),
    banner('args.ts') +
      `import type { JsonObject } from './scalars';\n` +
      enums.map((e) => `import type { ${e.name} } from './enums';`).join('\n') +
      '\n' +
      inputs.map((i) => `import type { ${i.name} } from './inputs';`).join('\n') +
      `\n\n${argsParts.length ? argsParts.join('\n\n') : 'export {};'}\n`,
  );

  const argTypeImports = [...objects, ...interfaces]
    .flatMap((o) => (o.fields ?? []).filter((f) => f.args?.length).map((f) => argsTypeName(o.name, f.name)))
    .map((n) => `import type { ${n} } from './args';`)
    .join('\n');
  writeFileSync(
    resolve(OUT_DIR, 'select.ts'),
    banner('select.ts') + `import type { AxiosRequestConfig } from 'axios';\n${argTypeImports}\n\n${selectParts.join('\n\n')}\n`,
  );

  // -------- field-args.ts (runtime) --------
  const fieldArgs: Record<string, Record<string, Record<string, string>>> = {};
  for (const obj of [...objects, ...interfaces]) {
    if (!obj.fields) continue;
    for (const f of obj.fields) {
      if (!f.args?.length) continue;
      const bucket = (fieldArgs[obj.name] ??= {});
      bucket[f.name] = Object.fromEntries(f.args.map((a) => [a.name, gqlTypeString(a.type)]));
    }
  }
  writeFileSync(
    resolve(OUT_DIR, 'field-args.ts'),
    banner('field-args.ts') +
      `export const FIELD_ARGS: Record<string, Record<string, Record<string, string>>> = ${JSON.stringify(fieldArgs, null, 2)};\n`,
  );

  // -------- field-types.ts (runtime parent.field -> childType name) --------
  const fieldTypes: Record<string, Record<string, string>> = {};
  for (const obj of [...objects, ...interfaces]) {
    if (!obj.fields) continue;
    for (const f of obj.fields) {
      const { named } = unwrap(f.type);
      if (named.kind === 'OBJECT' || named.kind === 'INTERFACE' || named.kind === 'UNION') {
        const bucket = (fieldTypes[obj.name] ??= {});
        bucket[f.name] = named.name!;
      }
    }
  }
  writeFileSync(
    resolve(OUT_DIR, 'field-types.ts'),
    banner('field-types.ts') +
      `export const FIELD_TYPES: Record<string, Record<string, string>> = ${JSON.stringify(fieldTypes, null, 2)};\n`,
  );

  // -------- wrappers.ts (runtime ItemsSerializer / DataSerializer unwrap map) --------
  writeFileSync(
    resolve(OUT_DIR, 'wrappers.ts'),
    banner('wrappers.ts') +
      `export const WRAPPERS: Record<string, { field: 'items' | 'data'; inner: string }> = ${JSON.stringify(wrappers, null, 2)};\n`,
  );

  // -------- root.ts --------
  const queryName = schema.queryType?.name ?? 'Query';
  const mutationName = schema.mutationType?.name ?? null;
  // Re-export the root Select types under stable names. When queryName === 'Query',
  // `QuerySelect` is already the right symbol — just `export { … }` it.
  const querySelectName = `${queryName}Select`;
  const mutationSelectName = mutationName ? `${mutationName}Select` : null;
  const aliasIfNeeded = (orig: string, target: string) => (orig === target ? orig : `${orig} as ${target}`);
  const reExports = [aliasIfNeeded(querySelectName, 'QuerySelect')];
  if (mutationSelectName) reExports.push(aliasIfNeeded(mutationSelectName, 'MutationSelect'));
  writeFileSync(
    resolve(OUT_DIR, 'root.ts'),
    banner('root.ts') +
      `export type { ${reExports.join(', ')} } from './select';\n` +
      (mutationSelectName ? '' : `export type MutationSelect = never;\n`) +
      `export const ROOT_QUERY_TYPE = ${JSON.stringify(queryName)};\n` +
      `export const ROOT_MUTATION_TYPE = ${JSON.stringify(mutationName)};\n`,
  );

  // -------- index.ts --------
  writeFileSync(
    resolve(OUT_DIR, 'index.ts'),
    banner('index.ts') +
      `export * from './scalars';\nexport * from './enums';\nexport * from './inputs';\nexport * from './schema';\nexport * from './select';\nexport * from './args';\nexport * from './root';\nexport { FIELD_ARGS } from './field-args';\nexport { FIELD_TYPES } from './field-types';\nexport { WRAPPERS } from './wrappers';\n`,
  );

  // -------- .gitignore (codegen output is reproducible) --------
  writeFileSync(resolve(OUT_DIR, '.gitignore'), '# Generated by scripts/gen-gql.ts\n*\n!.gitignore\n');

  console.log(
    `[gen-gql] wrote ${objects.length} objects, ${interfaces.length} interfaces, ${unions.length} unions, ${inputs.length} inputs, ${enums.length} enums → ${OUT_DIR}`,
  );
}

main();
